### ISSUE TITLE
Test for real image

### ISSUE THREAD

**Issue by lylllove** [yuanjunchai/IKC#15]
Thank you for your great job to share. I have made some test  for my  synthetic image data(some remote sensing image).And it worked well . I've got  2x，4x  model  of F,P,C model. 
I want to apply it to super resolution to actual data.  And I tried to modify the code of  test_IKC , while the mode of 'LQ','LQGTker'，‘SRker'  need  kernel_map or HR image except for  LR image. 
I wonder if you can give me some suggestion for the test of IKC  when I have LR image only.

**Comment by yuanjunchai** [comment]
Hi! The purpose of HR in test_IKC is just to calculate PSNR. If you would like to test actual data, you could just delete codes about HR. Thus, you could just get blind SR results of your actual LRs.

**Comment by lylllove** [comment]
I got it!
