### ISSUE TITLE
about random_batch_noise?

### ISSUE THREAD

**Issue by idealboy** [yuanjunchai/IKC#4]
Sir,

Have you haven the random_batch_noise function committed? thank you!

**Comment by yuanjunchai** [comment]
Yeah. It has fixed.
Any other problems?

**Comment by idealboy** [comment]
when calling SRMDPreprocessing, I found that only 'sig=2.6' was used to generate the LR images.

Should it use uniform sample for sig for each image according the original paper?

thank you very much.

**Comment by idealboy** [comment]
The kernel size is fixed
to 21×21. When applying on real world images, we use the
additive Gaussian noise with covariance σ = 15

Sorry, I think I could not make sure which parameter will represent this σ = 15, thank you ,sir!

**Comment by yuanjunchai** [comment]
> when calling SRMDPreprocessing, I found that only 'sig=2.6' was used to generate the LR images.
> 
> Should it use uniform sample for sig for each image according the original paper?
> 
> thank you very much.

'sigma=2.6' refers to fixed test kernel, you could change the setting according to the paper.

**Comment by yuanjunchai** [comment]
> The kernel size is fixed
> to 21×21. When applying on real world images, we use the
> additive Gaussian noise with covariance σ = 15
> 
> Sorry, I think I could not make sure which parameter will represent this σ = 15, thank you ,sir!

self.noise_high is sigma of noise

**Comment by idealboy** [comment]
> > The kernel size is fixed
> > to 21×21. When applying on real world images, we use the
> > additive Gaussian noise with covariance σ = 15
> > Sorry, I think I could not make sure which parameter will represent this σ = 15, thank you ,sir!
> 
> self.noise_high is sigma of noise

thank you , sir

**Comment by nanmehta** [comment]
Could u please help me what exactly is ground truth kernel?
as for Super-resolution we consider ground truth image to be the actually HR image and LR image to be the downsampled version? So my doubt is what have we actually consider to be a ground truth kernel?
