### ISSUE TITLE
PCA Matrix Generation

### ISSUE THREAD

**Issue by Dreamkeeper66666** [yuanjunchai/IKC#5]
Hi, thanks for your code! I am wondering how the PCA matrix was trained. Is it possible to include the code of this part as well? Thank you! @yuanjunchai

**Comment by yuanjunchai** [comment]
Hi! Please refer train_SFTMD.py, and then you could train your own PCA matrix.
 `    # create PCA matrix of enough kernel and save it, to ensure all kernel have same corresponding kernel maps
    batch_ker = util.random_batch_kernel(batch=30000, l=opt_F['kernel_size'], sig_min=opt_F['sig_min'], sig_max=opt_F['sig_max'], rate_iso=1.0, scaling=3, tensor=False)
    print('batch kernel shape: {}'.format(batch_ker.shape))
    b = np.size(batch_ker, 0)
    batch_ker = batch_ker.reshape((b, -1))
    pca_matrix = util.PCA(batch_ker, k=opt_F['code_length']).float()
    print('PCA matrix shape: {}'.format(pca_matrix.shape))
    torch.save(pca_matrix, './pca_matrix.pth')
    print('Save PCA matrix at: ./pca_matrix.pth')`
