### ISSUE TITLE
about the blur patch gerneate

### ISSUE THREAD

**Issue by yiyunchen** [yuanjunchai/IKC#6]
I am new to the blind super-resolution.
and i am confused about the data generate. 
may i ask is the blur image patch is generated by first get patch then blur?
and if i bluring the whole image and the get patch? is that suitable?
thank you!

**Comment by yuanjunchai** [comment]
Hi! These two methods are almost equal. The difference might occur in edges, which could be solved by reflection padding--'nn.ReflectionPad2d'.
